// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/loft-sh/test/pkg/client/clientset_generated/clientset/typed/test/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeTestV1 struct {
	*testing.Fake
}

func (c *FakeTestV1) ClusterRoles() v1.ClusterRoleInterface {
	return &FakeClusterRoles{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeTestV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
