export const DEVSPACE_GIT_REPOSITORY = "https://dev.khulnasoft.com"

export const DEFAULT_STATIC_COMMAND_CONFIG = {
  streamResponse: false,
  debug: false,
} as const
/** placeholder for arbitrary additional flags */
export const WORKSPACE_COMMAND_ADDITIONAL_FLAGS_KEY = "additionalFlags"

export const DEVSPACE_BINARY = "bin/devspace-cli"
export const DEVSPACE_COMMAND_LIST = "list"
export const DEVSPACE_COMMAND_STATUS = "status"
export const DEVSPACE_COMMAND_UP = "up"
export const DEVSPACE_COMMAND_STOP = "stop"
export const DEVSPACE_COMMAND_BUILD = "build"
export const DEVSPACE_COMMAND_DELETE = "delete"
export const DEVSPACE_COMMAND_PROVIDER = "provider"
export const DEVSPACE_COMMAND_IDE = "ide"
export const DEVSPACE_COMMAND_PRO = "pro"
export const DEVSPACE_COMMAND_OPTIONS = "options"
export const DEVSPACE_COMMAND_SET_OPTIONS = "set-options"
export const DEVSPACE_COMMAND_USE = "use"
export const DEVSPACE_COMMAND_ADD = "add"
export const DEVSPACE_COMMAND_HELPER = "helper"
export const DEVSPACE_COMMAND_UPDATE = "update"
export const DEVSPACE_COMMAND_CONTEXT = "context"
export const DEVSPACE_COMMAND_LOGIN = "login"
export const DEVSPACE_COMMAND_IMPORT_WORKSPACE = "import-workspace"
export const DEVSPACE_COMMAND_GET_WORKSPACE_NAME = "get-workspace-name"
export const DEVSPACE_COMMAND_GET_WORKSPACE_UID = "get-workspace-uid"
export const DEVSPACE_COMMAND_GET_WORKSPACE_CONFIG = "get-workspace-config"
export const DEVSPACE_COMMAND_GET_PROVIDER_NAME = "get-provider-name"
export const DEVSPACE_COMMAND_GET_PRO_NAME = "get-pro-name"
export const DEVSPACE_COMMAND_CHECK_PROVIDER_UPDATE = "check-provider-update"
export const DEVSPACE_COMMAND_TROUBLESHOOT = "troubleshoot"
export const DEVSPACE_FLAG_JSON_LOG_OUTPUT = "--log-output=json"
export const DEVSPACE_FLAG_JSON_OUTPUT = "--output=json"
export const DEVSPACE_FLAG_OPTION = "--option"
export const DEVSPACE_FLAG_FORCE = "--force"
export const DEVSPACE_FLAG_FORCE_BUILD = "--force-build"
export const DEVSPACE_FLAG_RECREATE = "--recreate"
export const DEVSPACE_FLAG_RESET = "--reset"
export const DEVSPACE_FLAG_IDE = "--ide"
export const DEVSPACE_FLAG_PROVIDER = "--provider"
export const DEVSPACE_FLAG_PROVIDER_OPTION = "--provider-option"
export const DEVSPACE_FLAG_ACCESS_KEY = "--access-key"
export const DEVSPACE_FLAG_PREBUILD_REPOSITORY = "--prebuild-repository"
export const DEVSPACE_FLAG_ID = "--id"
export const DEVSPACE_FLAG_SOURCE = "--source"
export const DEVSPACE_FLAG_DEBUG = "--debug"
export const DEVSPACE_FLAG_USE = "--use"
export const DEVSPACE_FLAG_NAME = "--name"
export const DEVSPACE_FLAG_SINGLE_MACHINE = "--single-machine"
export const DEVSPACE_FLAG_DRY = "--dry"
export const DEVSPACE_FLAG_RECONFIGURE = "--reconfigure"
export const DEVSPACE_FLAG_SKIP_REQUIRED = "--skip-required"
export const DEVSPACE_FLAG_TIMEOUT = "--timeout"
export const DEVSPACE_FLAG_DEVCONTAINER_PATH = "--devcontainer-path"
export const DEVSPACE_FLAG_WORKSPACE_ID = "--workspace-id"
export const DEVSPACE_FLAG_WORKSPACE_UID = "--workspace-uid"
export const DEVSPACE_FLAG_WORKSPACE_PROJECT = "--workspace-project"
export const DEVSPACE_FLAG_LOGIN = "--login"
export const DEVSPACE_FLAG_HOST = "--host"
export const DEVSPACE_FLAG_INSTANCE = "--instance"
export const DEVSPACE_FLAG_PROJECT = "--project"
export const DEVSPACE_FLAG_SKIP_PRO = "--skip-pro"
export const DEVSPACE_FLAG_DOTFILES = "--dotfiles"
export const DEVSPACE_FLAG_GIT_SIGNING_KEY = "--git-ssh-signing-key"
export const DEVSPACE_FLAG_FORCE_BROWSER = "--force-browser"

export const DEVSPACE_UI_ENV_VAR = "DEVSPACE_UI"
export const DEVSPACE_ADDITIONAL_ENV_VARS = "DEVSPACE_ADDITIONAL_ENV_VARS"
