// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "dev.khulnasoft.com/api/pkg/apis/management/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKhulnasoftUpgrades implements KhulnasoftUpgradeInterface
type FakeKhulnasoftUpgrades struct {
	Fake *FakeManagementV1
}

var khulnasoftupgradesResource = v1.SchemeGroupVersion.WithResource("khulnasoftupgrades")

var khulnasoftupgradesKind = v1.SchemeGroupVersion.WithKind("KhulnasoftUpgrade")

// Get takes name of the khulnasoftUpgrade, and returns the corresponding khulnasoftUpgrade object, and an error if there is any.
func (c *FakeKhulnasoftUpgrades) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.KhulnasoftUpgrade, err error) {
	emptyResult := &v1.KhulnasoftUpgrade{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(khulnasoftupgradesResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.KhulnasoftUpgrade), err
}

// List takes label and field selectors, and returns the list of KhulnasoftUpgrades that match those selectors.
func (c *FakeKhulnasoftUpgrades) List(ctx context.Context, opts metav1.ListOptions) (result *v1.KhulnasoftUpgradeList, err error) {
	emptyResult := &v1.KhulnasoftUpgradeList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(khulnasoftupgradesResource, khulnasoftupgradesKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.KhulnasoftUpgradeList{ListMeta: obj.(*v1.KhulnasoftUpgradeList).ListMeta}
	for _, item := range obj.(*v1.KhulnasoftUpgradeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested khulnasoftUpgrades.
func (c *FakeKhulnasoftUpgrades) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(khulnasoftupgradesResource, opts))
}

// Create takes the representation of a khulnasoftUpgrade and creates it.  Returns the server's representation of the khulnasoftUpgrade, and an error, if there is any.
func (c *FakeKhulnasoftUpgrades) Create(ctx context.Context, khulnasoftUpgrade *v1.KhulnasoftUpgrade, opts metav1.CreateOptions) (result *v1.KhulnasoftUpgrade, err error) {
	emptyResult := &v1.KhulnasoftUpgrade{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(khulnasoftupgradesResource, khulnasoftUpgrade, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.KhulnasoftUpgrade), err
}

// Update takes the representation of a khulnasoftUpgrade and updates it. Returns the server's representation of the khulnasoftUpgrade, and an error, if there is any.
func (c *FakeKhulnasoftUpgrades) Update(ctx context.Context, khulnasoftUpgrade *v1.KhulnasoftUpgrade, opts metav1.UpdateOptions) (result *v1.KhulnasoftUpgrade, err error) {
	emptyResult := &v1.KhulnasoftUpgrade{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(khulnasoftupgradesResource, khulnasoftUpgrade, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.KhulnasoftUpgrade), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKhulnasoftUpgrades) UpdateStatus(ctx context.Context, khulnasoftUpgrade *v1.KhulnasoftUpgrade, opts metav1.UpdateOptions) (result *v1.KhulnasoftUpgrade, err error) {
	emptyResult := &v1.KhulnasoftUpgrade{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceActionWithOptions(khulnasoftupgradesResource, "status", khulnasoftUpgrade, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.KhulnasoftUpgrade), err
}

// Delete takes name of the khulnasoftUpgrade and deletes it. Returns an error if one occurs.
func (c *FakeKhulnasoftUpgrades) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(khulnasoftupgradesResource, name, opts), &v1.KhulnasoftUpgrade{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKhulnasoftUpgrades) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(khulnasoftupgradesResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.KhulnasoftUpgradeList{})
	return err
}

// Patch applies the patch and returns the patched khulnasoftUpgrade.
func (c *FakeKhulnasoftUpgrades) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KhulnasoftUpgrade, err error) {
	emptyResult := &v1.KhulnasoftUpgrade{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(khulnasoftupgradesResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.KhulnasoftUpgrade), err
}
