// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	storagev1 "dev.khulnasoft.com/api/pkg/apis/storage/v1"
	versioned "dev.khulnasoft.com/api/pkg/clientset/versioned"
	internalinterfaces "dev.khulnasoft.com/api/pkg/informers/externalversions/internalinterfaces"
	v1 "dev.khulnasoft.com/api/pkg/listers/storage/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DevSpaceWorkspaceInstanceInformer provides access to a shared informer and lister for
// DevSpaceWorkspaceInstances.
type DevSpaceWorkspaceInstanceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DevSpaceWorkspaceInstanceLister
}

type devSpaceWorkspaceInstanceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDevSpaceWorkspaceInstanceInformer constructs a new informer for DevSpaceWorkspaceInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDevSpaceWorkspaceInstanceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDevSpaceWorkspaceInstanceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDevSpaceWorkspaceInstanceInformer constructs a new informer for DevSpaceWorkspaceInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDevSpaceWorkspaceInstanceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1().DevSpaceWorkspaceInstances(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1().DevSpaceWorkspaceInstances(namespace).Watch(context.TODO(), options)
			},
		},
		&storagev1.DevSpaceWorkspaceInstance{},
		resyncPeriod,
		indexers,
	)
}

func (f *devSpaceWorkspaceInstanceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDevSpaceWorkspaceInstanceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *devSpaceWorkspaceInstanceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&storagev1.DevSpaceWorkspaceInstance{}, f.defaultInformer)
}

func (f *devSpaceWorkspaceInstanceInformer) Lister() v1.DevSpaceWorkspaceInstanceLister {
	return v1.NewDevSpaceWorkspaceInstanceLister(f.Informer().GetIndexer())
}
