// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "dev.khulnasoft.com/api/pkg/apis/management/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// DevSpaceEnvironmentTemplateLister helps list DevSpaceEnvironmentTemplates.
// All objects returned here must be treated as read-only.
type DevSpaceEnvironmentTemplateLister interface {
	// List lists all DevSpaceEnvironmentTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DevSpaceEnvironmentTemplate, err error)
	// Get retrieves the DevSpaceEnvironmentTemplate from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.DevSpaceEnvironmentTemplate, error)
	DevSpaceEnvironmentTemplateListerExpansion
}

// devSpaceEnvironmentTemplateLister implements the DevSpaceEnvironmentTemplateLister interface.
type devSpaceEnvironmentTemplateLister struct {
	listers.ResourceIndexer[*v1.DevSpaceEnvironmentTemplate]
}

// NewDevSpaceEnvironmentTemplateLister returns a new DevSpaceEnvironmentTemplateLister.
func NewDevSpaceEnvironmentTemplateLister(indexer cache.Indexer) DevSpaceEnvironmentTemplateLister {
	return &devSpaceEnvironmentTemplateLister{listers.New[*v1.DevSpaceEnvironmentTemplate](indexer, v1.Resource("devspaceenvironmenttemplate"))}
}
