// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "dev.khulnasoft.com/api/pkg/apis/management/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// DevSpaceWorkspaceInstanceLister helps list DevSpaceWorkspaceInstances.
// All objects returned here must be treated as read-only.
type DevSpaceWorkspaceInstanceLister interface {
	// List lists all DevSpaceWorkspaceInstances in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DevSpaceWorkspaceInstance, err error)
	// DevSpaceWorkspaceInstances returns an object that can list and get DevSpaceWorkspaceInstances.
	DevSpaceWorkspaceInstances(namespace string) DevSpaceWorkspaceInstanceNamespaceLister
	DevSpaceWorkspaceInstanceListerExpansion
}

// devSpaceWorkspaceInstanceLister implements the DevSpaceWorkspaceInstanceLister interface.
type devSpaceWorkspaceInstanceLister struct {
	listers.ResourceIndexer[*v1.DevSpaceWorkspaceInstance]
}

// NewDevSpaceWorkspaceInstanceLister returns a new DevSpaceWorkspaceInstanceLister.
func NewDevSpaceWorkspaceInstanceLister(indexer cache.Indexer) DevSpaceWorkspaceInstanceLister {
	return &devSpaceWorkspaceInstanceLister{listers.New[*v1.DevSpaceWorkspaceInstance](indexer, v1.Resource("devspaceworkspaceinstance"))}
}

// DevSpaceWorkspaceInstances returns an object that can list and get DevSpaceWorkspaceInstances.
func (s *devSpaceWorkspaceInstanceLister) DevSpaceWorkspaceInstances(namespace string) DevSpaceWorkspaceInstanceNamespaceLister {
	return devSpaceWorkspaceInstanceNamespaceLister{listers.NewNamespaced[*v1.DevSpaceWorkspaceInstance](s.ResourceIndexer, namespace)}
}

// DevSpaceWorkspaceInstanceNamespaceLister helps list and get DevSpaceWorkspaceInstances.
// All objects returned here must be treated as read-only.
type DevSpaceWorkspaceInstanceNamespaceLister interface {
	// List lists all DevSpaceWorkspaceInstances in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DevSpaceWorkspaceInstance, err error)
	// Get retrieves the DevSpaceWorkspaceInstance from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.DevSpaceWorkspaceInstance, error)
	DevSpaceWorkspaceInstanceNamespaceListerExpansion
}

// devSpaceWorkspaceInstanceNamespaceLister implements the DevSpaceWorkspaceInstanceNamespaceLister
// interface.
type devSpaceWorkspaceInstanceNamespaceLister struct {
	listers.ResourceIndexer[*v1.DevSpaceWorkspaceInstance]
}
