// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "dev.khulnasoft.com/api/pkg/apis/management/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// KhulnasoftUpgradeLister helps list KhulnasoftUpgrades.
// All objects returned here must be treated as read-only.
type KhulnasoftUpgradeLister interface {
	// List lists all KhulnasoftUpgrades in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.KhulnasoftUpgrade, err error)
	// Get retrieves the KhulnasoftUpgrade from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.KhulnasoftUpgrade, error)
	KhulnasoftUpgradeListerExpansion
}

// khulnasoftUpgradeLister implements the KhulnasoftUpgradeLister interface.
type khulnasoftUpgradeLister struct {
	listers.ResourceIndexer[*v1.KhulnasoftUpgrade]
}

// NewKhulnasoftUpgradeLister returns a new KhulnasoftUpgradeLister.
func NewKhulnasoftUpgradeLister(indexer cache.Indexer) KhulnasoftUpgradeLister {
	return &khulnasoftUpgradeLister{listers.New[*v1.KhulnasoftUpgrade](indexer, v1.Resource("khulnasoftupgrade"))}
}
