// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	managementv1 "dev.khulnasoft.com/api/pkg/apis/management/v1"
	versioned "dev.khulnasoft.com/api/pkg/clientset/versioned"
	internalinterfaces "dev.khulnasoft.com/api/pkg/informers/externalversions/internalinterfaces"
	v1 "dev.khulnasoft.com/api/pkg/listers/management/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DevSpaceWorkspacePresetInformer provides access to a shared informer and lister for
// DevSpaceWorkspacePresets.
type DevSpaceWorkspacePresetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DevSpaceWorkspacePresetLister
}

type devSpaceWorkspacePresetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewDevSpaceWorkspacePresetInformer constructs a new informer for DevSpaceWorkspacePreset type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDevSpaceWorkspacePresetInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDevSpaceWorkspacePresetInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredDevSpaceWorkspacePresetInformer constructs a new informer for DevSpaceWorkspacePreset type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDevSpaceWorkspacePresetInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().DevSpaceWorkspacePresets().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().DevSpaceWorkspacePresets().Watch(context.TODO(), options)
			},
		},
		&managementv1.DevSpaceWorkspacePreset{},
		resyncPeriod,
		indexers,
	)
}

func (f *devSpaceWorkspacePresetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDevSpaceWorkspacePresetInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *devSpaceWorkspacePresetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&managementv1.DevSpaceWorkspacePreset{}, f.defaultInformer)
}

func (f *devSpaceWorkspacePresetInformer) Lister() v1.DevSpaceWorkspacePresetLister {
	return v1.NewDevSpaceWorkspacePresetLister(f.Informer().GetIndexer())
}
