// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	managementv1 "dev.khulnasoft.com/api/pkg/apis/management/v1"
	versioned "dev.khulnasoft.com/api/pkg/clientset/versioned"
	internalinterfaces "dev.khulnasoft.com/api/pkg/informers/externalversions/internalinterfaces"
	v1 "dev.khulnasoft.com/api/pkg/listers/management/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DevSpaceWorkspaceTemplateInformer provides access to a shared informer and lister for
// DevSpaceWorkspaceTemplates.
type DevSpaceWorkspaceTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DevSpaceWorkspaceTemplateLister
}

type devSpaceWorkspaceTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewDevSpaceWorkspaceTemplateInformer constructs a new informer for DevSpaceWorkspaceTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDevSpaceWorkspaceTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDevSpaceWorkspaceTemplateInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredDevSpaceWorkspaceTemplateInformer constructs a new informer for DevSpaceWorkspaceTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDevSpaceWorkspaceTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().DevSpaceWorkspaceTemplates().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().DevSpaceWorkspaceTemplates().Watch(context.TODO(), options)
			},
		},
		&managementv1.DevSpaceWorkspaceTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *devSpaceWorkspaceTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDevSpaceWorkspaceTemplateInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *devSpaceWorkspaceTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&managementv1.DevSpaceWorkspaceTemplate{}, f.defaultInformer)
}

func (f *devSpaceWorkspaceTemplateInformer) Lister() v1.DevSpaceWorkspaceTemplateLister {
	return v1.NewDevSpaceWorkspaceTemplateLister(f.Informer().GetIndexer())
}
