// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	managementv1 "dev.khulnasoft.com/api/pkg/apis/management/v1"
	versioned "dev.khulnasoft.com/api/pkg/clientset/versioned"
	internalinterfaces "dev.khulnasoft.com/api/pkg/informers/externalversions/internalinterfaces"
	v1 "dev.khulnasoft.com/api/pkg/listers/management/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KhulnasoftUpgradeInformer provides access to a shared informer and lister for
// KhulnasoftUpgrades.
type KhulnasoftUpgradeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.KhulnasoftUpgradeLister
}

type khulnasoftUpgradeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewKhulnasoftUpgradeInformer constructs a new informer for KhulnasoftUpgrade type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKhulnasoftUpgradeInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKhulnasoftUpgradeInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredKhulnasoftUpgradeInformer constructs a new informer for KhulnasoftUpgrade type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKhulnasoftUpgradeInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().KhulnasoftUpgrades().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().KhulnasoftUpgrades().Watch(context.TODO(), options)
			},
		},
		&managementv1.KhulnasoftUpgrade{},
		resyncPeriod,
		indexers,
	)
}

func (f *khulnasoftUpgradeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKhulnasoftUpgradeInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *khulnasoftUpgradeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&managementv1.KhulnasoftUpgrade{}, f.defaultInformer)
}

func (f *khulnasoftUpgradeInformer) Lister() v1.KhulnasoftUpgradeLister {
	return v1.NewKhulnasoftUpgradeLister(f.Informer().GetIndexer())
}
