// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	managementv1 "dev.khulnasoft.com/api/pkg/apis/management/v1"
	versioned "dev.khulnasoft.com/api/pkg/clientset/versioned"
	internalinterfaces "dev.khulnasoft.com/api/pkg/informers/externalversions/internalinterfaces"
	v1 "dev.khulnasoft.com/api/pkg/listers/management/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RegisterVirtualClusterInformer provides access to a shared informer and lister for
// RegisterVirtualClusters.
type RegisterVirtualClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.RegisterVirtualClusterLister
}

type registerVirtualClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewRegisterVirtualClusterInformer constructs a new informer for RegisterVirtualCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRegisterVirtualClusterInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRegisterVirtualClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredRegisterVirtualClusterInformer constructs a new informer for RegisterVirtualCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRegisterVirtualClusterInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().RegisterVirtualClusters().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().RegisterVirtualClusters().Watch(context.TODO(), options)
			},
		},
		&managementv1.RegisterVirtualCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *registerVirtualClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRegisterVirtualClusterInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *registerVirtualClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&managementv1.RegisterVirtualCluster{}, f.defaultInformer)
}

func (f *registerVirtualClusterInformer) Lister() v1.RegisterVirtualClusterLister {
	return v1.NewRegisterVirtualClusterLister(f.Informer().GetIndexer())
}
