// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	managementv1 "dev.khulnasoft.com/api/pkg/apis/management/v1"
	versioned "dev.khulnasoft.com/api/pkg/clientset/versioned"
	internalinterfaces "dev.khulnasoft.com/api/pkg/informers/externalversions/internalinterfaces"
	v1 "dev.khulnasoft.com/api/pkg/listers/management/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VirtualClusterTemplateInformer provides access to a shared informer and lister for
// VirtualClusterTemplates.
type VirtualClusterTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.VirtualClusterTemplateLister
}

type virtualClusterTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewVirtualClusterTemplateInformer constructs a new informer for VirtualClusterTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVirtualClusterTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVirtualClusterTemplateInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredVirtualClusterTemplateInformer constructs a new informer for VirtualClusterTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVirtualClusterTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().VirtualClusterTemplates().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().VirtualClusterTemplates().Watch(context.TODO(), options)
			},
		},
		&managementv1.VirtualClusterTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *virtualClusterTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVirtualClusterTemplateInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *virtualClusterTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&managementv1.VirtualClusterTemplate{}, f.defaultInformer)
}

func (f *virtualClusterTemplateInformer) Lister() v1.VirtualClusterTemplateLister {
	return v1.NewVirtualClusterTemplateLister(f.Informer().GetIndexer())
}
