name: Upload Stripe Features

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  upload-features:
    runs-on: ubuntu-latest
    env:
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Upload features
        run: |
          go run ./hack/upstream-features/upload.go
