// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "dev.khulnasoft.com/api/pkg/apis/storage/v1"
	scheme "dev.khulnasoft.com/api/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DevSpaceWorkspacePresetsGetter has a method to return a DevSpaceWorkspacePresetInterface.
// A group's client should implement this interface.
type DevSpaceWorkspacePresetsGetter interface {
	DevSpaceWorkspacePresets() DevSpaceWorkspacePresetInterface
}

// DevSpaceWorkspacePresetInterface has methods to work with DevSpaceWorkspacePreset resources.
type DevSpaceWorkspacePresetInterface interface {
	Create(ctx context.Context, devSpaceWorkspacePreset *v1.DevSpaceWorkspacePreset, opts metav1.CreateOptions) (*v1.DevSpaceWorkspacePreset, error)
	Update(ctx context.Context, devSpaceWorkspacePreset *v1.DevSpaceWorkspacePreset, opts metav1.UpdateOptions) (*v1.DevSpaceWorkspacePreset, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.DevSpaceWorkspacePreset, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DevSpaceWorkspacePresetList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DevSpaceWorkspacePreset, err error)
	DevSpaceWorkspacePresetExpansion
}

// devSpaceWorkspacePresets implements DevSpaceWorkspacePresetInterface
type devSpaceWorkspacePresets struct {
	*gentype.ClientWithList[*v1.DevSpaceWorkspacePreset, *v1.DevSpaceWorkspacePresetList]
}

// newDevSpaceWorkspacePresets returns a DevSpaceWorkspacePresets
func newDevSpaceWorkspacePresets(c *StorageV1Client) *devSpaceWorkspacePresets {
	return &devSpaceWorkspacePresets{
		gentype.NewClientWithList[*v1.DevSpaceWorkspacePreset, *v1.DevSpaceWorkspacePresetList](
			"devspaceworkspacepresets",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1.DevSpaceWorkspacePreset { return &v1.DevSpaceWorkspacePreset{} },
			func() *v1.DevSpaceWorkspacePresetList { return &v1.DevSpaceWorkspacePresetList{} }),
	}
}
